import React from "react";

/**
 * PUBLIC_INTERFACE
 * About: Static information page for EchoGuard app (themed for PrivSecure AI)
 * Styled as Settings: white 'surface' card, large header, clear sections and lists.
 * No form/input/logic—pure info only.
 */
function About() {
  return (
    <div
      className="container"
      style={{
        marginTop: 42,
        maxWidth: 720,
        padding: "38px 12px 44px 12px",
        background: "var(--surface)",
        borderRadius: "var(--border-radius)",
        boxShadow: "var(--box-shadow)",
        minHeight: 430,
        color: "var(--text-primary)",
      }}
    >
      <h1
        className="title"
        style={{
          color: "var(--primary)",
          textShadow: "0 0 18px var(--accent), 0 0 2px var(--primary)",
          fontWeight: 900,
          fontSize: "2.12rem",
          marginBottom: 12,
          letterSpacing: ".04em",
        }}
      >
        About EchoGuard <span aria-label="shield emoji" role="img">🛡️</span>
      </h1>
      <div
        className="description"
        style={{
          marginBottom: 23,
        }}
      >
        EchoGuard is your personal, AI-powered security suite dedicated to keeping your digital footprint private, safe, and under your full control. Our mission is to deliver a privacy-first experience—empowering you with insights and tools normally reserved for cybersecurity pros.
      </div>

      <h2 style={{
        color: "var(--secondary)",
        fontSize: "1.32rem",
        fontWeight: 700,
        marginTop: 18,
        marginBottom: 8,
        letterSpacing: ".02em",
        textShadow: "0 0 9px var(--accent)",
      }}>
        Key Features
      </h2>
      <ul style={{
        fontSize: "1.13rem",
        color: "var(--text-secondary)",
        marginLeft: 18,
        marginBottom: 20,
      }}>
        <li style={{ marginBottom: 8 }}>
          <strong>Exposure Dashboard</strong>: Real-time risk score, trend analysis, instant alerts.
        </li>
        <li style={{ marginBottom: 8 }}>
          <strong>AI Privacy Plan</strong>: Personalized checklist—autogenerated by advanced AI.
        </li>
        <li style={{ marginBottom: 8 }}>
          <strong>Digital Twin Scanner</strong>: Detects impersonations and identity clones.
        </li>
        <li style={{ marginBottom: 8 }}>
          <strong>Dark Web Monitor</strong>: Finds your leaked credentials—before hackers do.
        </li>
        <li style={{ marginBottom: 8 }}>
          <strong>Badge System</strong>: Recognizes your privacy achievements and progress.
        </li>
        <li style={{ marginBottom: 8 }}>
          <strong>Third-Party Risk Manager</strong>: Reveals data sharing with connected apps.
        </li>
      </ul>

      <h2 style={{
        color: "var(--secondary)",
        fontSize: "1.2rem",
        fontWeight: 700,
        marginTop: 10,
        marginBottom: 7,
        letterSpacing: ".018em",
        textShadow: "0 0 7px var(--accent)"
      }}>
        Why EchoGuard? <span role="img" aria-label="lock emoji">🔒</span>
      </h2>
      <ul style={{
        fontSize: "1.12rem",
        color: "var(--text-secondary)",
        marginLeft: 18,
        marginBottom: 21,
      }}>
        <li style={{marginBottom: 6}}>
          <strong>Privacy by Default</strong>: Your data stays on your device—always.
        </li>
        <li style={{marginBottom: 6}}>
          <strong>No tracking, no ads</strong>: You’re our customer, not the product.
        </li>
        <li style={{marginBottom: 6}}>
          <strong>Open AI, Transparent security</strong>: Auditable, explainable actions. You’re in control.
        </li>
        <li>
          <strong>Secure by design</strong>: Latest encryption and best practices, no shortcuts.
        </li>
      </ul>

      <h2 style={{
        color: "var(--primary)",
        fontSize: "1.18rem",
        fontWeight: 800,
        marginTop: 10,
        marginBottom: 7,
        textShadow: "0 0 9px var(--secondary)"
      }}>
        Our Mission <span role="img" aria-label="sparkle">✨</span>
      </h2>
      <p style={{
        color: "var(--text-secondary)",
        fontSize: "1.09rem",
        maxWidth: 520,
        marginBottom: 14,
      }}>
        To make world-class security straightforward for everyone. We believe digital privacy is your right—not a luxury—and EchoGuard will never sell, trade, or misuse your personal information.
      </p>

      <div style={{
        background: "#eefafd",
        borderRadius: 11,
        color: "var(--secondary)",
        fontWeight: 670,
        padding: "15px 20px",
        border: "1.4px solid var(--border-color)",
        fontSize: "1.05rem",
        marginTop: 10,
        boxShadow: "0 0 7px 1px var(--accent)"
      }}>
        {/* Community/Feedback line */}
        Got ideas, concerns, or want to contribute? Reach us at <a href="mailto:hello@echoguard.ai">hello@echoguard.ai</a> or join our open source community!
      </div>
    </div>
  );
}

export default About;
